# solstone-swift build targets

.PHONY: generate build-metadata-bootstrap build-metadata build build-generic release sim sim-json sim-ipad sim-ipad-json watch-sim watch-sim-json sim-create sim-delete sim-state sim-launch verify-capture-audio test ui-test integration-test integration-test-push integration-test-observer integration-test-onboarding integration-test-live test-one test-build test-fast ci ci-watch ci-ipad sim-shots-ipad ci-selftest brand-sync \
			       release-distribution ipa-appstore testflight-upload testflight-release testflight check-asc-config \
			       install deploy launch cycle run unlock \
			       sim-shots sim-widget-shots screenshot logs logs-collect log-show crash devices deps clean signing-check

SCHEME    ?= solstone-swift
PROJECT   ?= solstone-swift.xcodeproj
comma := ,
BUNDLE_ID ?= app.solstone.swift
TEAM_ID   ?= 7QCG8V4M6H
DEVICE    ?= 1776B0A9-E149-52A1-9F6F-04CCDE223940
SIM       ?= iPhone 17 Pro
SIM_IPAD  ?= iPad Pro 13-inch (M4)
SIM_WATCH ?= Apple Watch Series 11 (46mm)
SIM_UDID ?=
SIM_DESTINATION ?= $(if $(strip $(SIM_UDID)),platform=iOS Simulator$(comma)id=$(SIM_UDID),platform=iOS Simulator$(comma)name=$(SIM))
SIM_RUN_NAME ?= solstone-swift-manual
SIM_UDID_FILE ?= build/manual-sim.udid
SIM_LOG_WINDOW ?= 5m
ARCHIVE   ?= build/solstone-swift.xcarchive
APP       ?= $(ARCHIVE)/Products/Applications/solstone-swift.app
LOG_SUB   ?= app.solstone.swift
KEYCHAIN  ?= ~/Library/Keychains/login.keychain-db
DERIVED   ?= DerivedData
BUILD_METADATA ?= config/BuildMetadata.generated.xcconfig
PACKAGE_RESOLVED ?= $(PROJECT)/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
SIM_APP    = $(DERIVED)/Build/Products/Debug-iphonesimulator/$(SCHEME).app
DEV_APP    = $(DERIVED)/Build/Products/Debug-iphoneos/$(SCHEME).app
WIDGET_SHOTS_OUT ?= /var/tmp/solstone-widget-shots-$(notdir $(CURDIR))
DEVICE_LOG ?= /tmp/solstone-swift.log
# Brand asset source — REQUIRED by `make brand-sync` (no default); set BRAND_DIR=/path/to/brand
BRAND_DIR  ?=

# --- App Store Connect / TestFlight (operator config) ---
# The pipeline below is generic; the account-specific values it needs are NOT
# committed. To use `make testflight`, create config/testflight.env (gitignored)
# defining ASC_KEY_ID, ASC_ISSUER, ASC_KEY_PATH, and TESTFLIGHT_GROUP for your
# own App Store Connect account. See config/testflight.env.example for the format.
-include config/testflight.env

ARCHIVE_DISTRIBUTION ?= build/solstone-swift-distribution.xcarchive
TESTFLIGHT_NOTIFY    ?= false

# --- CI test runner (host-side-flake resistance; see test/run_ci_tests.sh) ---
# `make ci` runs the test phase through a timeout-guarded, retry-once wrapper that
# never hangs and never masks a real test failure. The UITest target intermittently
# wedges/flakes at the HOST RUNNER under simulator load (0% CPU accessibility hang,
# or exit 65 with 0 recorded failures) — these vars tune the wrapper. Pin a different
# runtime by overriding CI_SIM_RUNTIME (e.g. ...SimRuntime.iOS-26-4).
CI_SIM_NAME        ?= solstone-swift-ci
CI_SIM_DEVICETYPE  ?= com.apple.CoreSimulator.SimDeviceType.iPhone-17-Pro
CI_SIM_RUNTIME     ?= com.apple.CoreSimulator.SimRuntime.iOS-26-5
CI_WATCH_SIM_NAME        ?= solstone-watch-ci
CI_WATCH_SIM_DEVICETYPE  ?= com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-11-46mm
CI_WATCH_SIM_RUNTIME     ?= com.apple.CoreSimulator.SimRuntime.watchOS-26-5
# The iPad lane (`make ci-ipad`) shares CI_SIM_RUNTIME and the default iOS Simulator
# platform with the iPhone lane; only the device type differs. It is deliberately NOT
# chained into `ci` — a third full lane on every run is a cost only the iPad work needs.
CI_IPAD_SIM_NAME         ?= solstone-ipad-ci
CI_IPAD_SIM_DEVICETYPE   ?= com.apple.CoreSimulator.SimDeviceType.iPad-Pro-13-inch-M4-8GB
CI_ATTEMPT_TIMEOUT ?= 1200
CI_MAX_ATTEMPTS    ?= 2

# --- Project setup ---

build-metadata-bootstrap:
	@mkdir -p "$$(dirname "$(BUILD_METADATA)")"
	@commit=$$(git rev-parse HEAD 2>/dev/null || echo unknown); \
	{ \
		printf '%s\n' '// generated by make build-metadata'; \
		printf 'SOLSTONE_SOURCE_COMMIT = %s\n' "$$commit"; \
		printf 'SOLSTONE_BUILD_CONFIGURATION = $$(CONFIGURATION)\n'; \
		printf 'SOLSTONE_SPL_SWIFT_IDENTITY = spl-swift\n'; \
		printf 'SOLSTONE_SPL_SWIFT_VERSION = unknown\n'; \
		printf 'SOLSTONE_SPL_SWIFT_REVISION = unknown\n'; \
	} > "$(BUILD_METADATA)"

build-metadata: build-metadata-bootstrap
	@set -eu; \
	commit=$$(git rev-parse HEAD 2>/dev/null || echo unknown); \
	metadata=$$(/usr/bin/python3 -c 'import json, sys; data=json.load(open(sys.argv[1])); pin=next((p for p in data.get("pins", []) if p.get("identity") == "spl-swift"), None); state=(pin or {}).get("state", {}); version=state.get("version"); revision=state.get("revision"); assert version and revision, "missing spl-swift package metadata"; print(version); print(revision)' "$(PACKAGE_RESOLVED)"); \
	version=$$(printf '%s\n' "$$metadata" | sed -n '1p'); \
	revision=$$(printf '%s\n' "$$metadata" | sed -n '2p'); \
	{ \
		printf '%s\n' '// generated by make build-metadata'; \
		printf 'SOLSTONE_SOURCE_COMMIT = %s\n' "$$commit"; \
		printf 'SOLSTONE_BUILD_CONFIGURATION = $$(CONFIGURATION)\n'; \
		printf 'SOLSTONE_SPL_SWIFT_IDENTITY = spl-swift\n'; \
		printf 'SOLSTONE_SPL_SWIFT_VERSION = %s\n' "$$version"; \
		printf 'SOLSTONE_SPL_SWIFT_REVISION = %s\n' "$$revision"; \
	} > "$(BUILD_METADATA)"

generate: build-metadata-bootstrap
	xcodegen generate

install: deps

deps: generate
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'generic/platform=iOS' \
		-resolvePackageDependencies
	$(MAKE) build-metadata

# Re-vendor brand SVGs from the canonical source — run locally when the brand
# spec updates, then commit the diff. dest-path:source-stem, mirroring
# solstone-macos's BRAND_SVGS convention: Swift's destinations are nested
# per-imageset paths with fixed Xcode-catalog filenames rather than a flat
# assets/ dir, so dest carries the full relative path, not a bare stem.
BRAND_SVGS = Sources/Assets.xcassets/SolWordmark.imageset/sol-wordmark.svg:mark \
	Sources/Assets.xcassets/SolWordmark.imageset/sol-wordmark-white.svg:mark-white \
	SolstoneWatchComplication/Assets.xcassets/MarkHealthy.imageset/mark.svg:mark \
	SolstoneWatchComplication/Assets.xcassets/MarkAttention.imageset/mark-attention.svg:mark-attention \
	SolstoneWatchComplication/Assets.xcassets/MarkPaused.imageset/mark-paused.svg:mark-paused \
	SolstoneWatchComplication/Assets.xcassets/MarkConnecting.imageset/mark-connecting.svg:mark-connecting \
	SolstoneWatchComplication/Assets.xcassets/MarkOffline.imageset/mark-offline.svg:mark-offline \
	Watch/Assets.xcassets/SolRingActive.imageset/sol-ring-active.svg:mark \
	Watch/Assets.xcassets/SolRingPaused.imageset/sol-ring-paused.svg:mark-paused \
	Watch/Assets.xcassets/SolRingAlert.imageset/sol-ring-alert.svg:mark-attention \
	Watch/Assets.xcassets/SolRingConnecting.imageset/sol-ring-connecting.svg:mark-connecting
brand-sync:
	@test -n "$(BRAND_DIR)" || { echo "brand: BRAND_DIR is required — point it at your sol brand asset directory (BRAND_DIR=/path/to/brand make brand-sync)"; exit 1; }
	@test -d "$(BRAND_DIR)" || { echo "brand: BRAND_DIR=$(BRAND_DIR) not found"; exit 1; }
	@set -e; for pair in $(BRAND_SVGS); do \
	  cp "$(BRAND_DIR)/$${pair#*:}.svg" "$${pair%%:*}"; \
	done
	# unified sol app icon (wordmark, full-bleed cream master, locked 2026-06-25). iOS
	# auto-masks to the squircle — keep full-bleed, do NOT pre-round. Same 1024 cream
	# master feeds the watch AppIcon too — PNG, a second destination family the stem
	# list above doesn't cover, left explicit rather than folded in.
	cp "$(BRAND_DIR)/app-icon/png-cream/app-icon-cream-1024.png" Sources/Assets.xcassets/AppIcon.appiconset/sol-app-icon-1024.png
	cp "$(BRAND_DIR)/app-icon/png-cream/app-icon-cream-1024.png" Watch/Assets.xcassets/AppIcon.appiconset/sol-app-icon-1024.png
	@echo "brand: synced from $(BRAND_DIR)"

# --- Keychain (required for device builds over SSH) ---

unlock:
	@security find-identity -p codesigning -v 2>/dev/null | grep -q "Apple Development" || \
		{ echo "error: Keychain locked or no signing identity. Unlock in the build window:"; \
		  echo "  security unlock-keychain ~/Library/Keychains/login.keychain-db"; exit 1; }
	@echo "Keychain: signing identity accessible"

# --- Simulator (no device/signing needed) ---

sim-create:
	@set -eu; \
		mkdir -p "$$(dirname "$(SIM_UDID_FILE)")"; \
		test ! -s "$(SIM_UDID_FILE)" || { echo "error: simulator ownership file already exists: $(SIM_UDID_FILE)"; exit 1; }; \
		udid=""; \
		cleanup() { if [ -n "$$udid" ] && [ ! -s "$(SIM_UDID_FILE)" ]; then xcrun simctl delete "$$udid" >/dev/null 2>&1 || true; fi; }; \
		trap cleanup EXIT; \
		udid=$$(xcrun simctl create "$(SIM_RUN_NAME)" "$(CI_SIM_DEVICETYPE)" "$(CI_SIM_RUNTIME)"); \
		printf '%s\n' "$$udid" >"$(SIM_UDID_FILE)"; \
		trap - EXIT; \
		printf '%s\n' "$$udid"

sim-delete:
	@set -eu; \
		test -s "$(SIM_UDID_FILE)" || { echo "error: simulator ownership file is missing: $(SIM_UDID_FILE)"; exit 1; }; \
		owned_udid=$$(cat "$(SIM_UDID_FILE)"); \
		udid='$(SIM_UDID)'; \
		if [ -z "$$udid" ]; then \
			udid="$$owned_udid"; \
		fi; \
		test "$$udid" = "$$owned_udid" || { echo "error: simulator ownership mismatch requested=$$udid recorded=$$owned_udid"; exit 1; }; \
		devices_json=$$(mktemp -t solstone-sim-devices.XXXXXX); \
		trap 'rm -f "$$devices_json"' EXIT; \
		xcrun simctl list devices -j >"$$devices_json"; \
		actual_name=$$(jq -r --arg udid "$$udid" 'first(.devices[][] | select(.udid == $$udid) | .name) // ""' "$$devices_json"); \
		test "$$actual_name" = "$(SIM_RUN_NAME)" || { echo "error: simulator ownership mismatch udid=$$udid expected=$(SIM_RUN_NAME) actual=$$actual_name"; exit 1; }; \
		xcrun simctl shutdown "$$udid" >/dev/null 2>&1 || true; \
		xcrun simctl delete "$$udid"; \
		if [ -s "$(SIM_UDID_FILE)" ] && [ "$$(cat "$(SIM_UDID_FILE)")" = "$$udid" ]; then rm -f "$(SIM_UDID_FILE)"; fi; \
		rm -f "$$devices_json"; \
		trap - EXIT

sim-state:
	@set -eu; \
		udid='$(SIM_UDID)'; \
		if [ -z "$$udid" ]; then \
			test -s "$(SIM_UDID_FILE)" || { echo "error: simulator ownership file is missing: $(SIM_UDID_FILE)"; exit 1; }; \
			udid=$$(cat "$(SIM_UDID_FILE)"); \
		fi; \
		root=$$(xcrun simctl get_app_container "$$udid" $(BUNDLE_ID) group.app.solstone.swift); \
		for directory in MobileSegment Transfers; do \
			if [ -d "$$root/$$directory" ]; then \
				find "$$root/$$directory" -maxdepth 4 -type f -print | LC_ALL=C sort; \
			fi; \
		done; \
		for file in "$$root"/MobileSegment/failed/*/failure.json "$$root"/MobileSegment/failed/*/manifest.json "$$root"/Transfers/attention/*/manifest.json; do \
			[ -f "$$file" ] || continue; \
			echo "--- $$file"; \
			jq -c . "$$file"; \
		done; \
		xcrun simctl spawn "$$udid" log show --style compact --last '$(SIM_LOG_WINDOW)' \
			--predicate 'subsystem == "$(LOG_SUB)"'

# Host-side Control Center artifact check: proves duration/bytes, not a microphone-input connection.
verify-capture-audio:
	@SIM_UDID='$(SIM_UDID)' SIM_UDID_FILE='$(SIM_UDID_FILE)' BUNDLE_ID='$(BUNDLE_ID)' zsh test/verify_capture_audio.sh

sim: deps
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination '$(SIM_DESTINATION)' \
		-derivedDataPath $(DERIVED) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build

sim-json: deps
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM)' \
		-derivedDataPath $(DERIVED) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build 2>&1 | xcsift

sim-ipad: deps
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM_IPAD)' \
		-derivedDataPath $(DERIVED) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build

sim-ipad-json: deps
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM_IPAD)' \
		-derivedDataPath $(DERIVED) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build 2>&1 | xcsift

watch-sim: deps
	xcodebuild -project $(PROJECT) -scheme SolstoneWatch \
		-skipMacroValidation \
		-destination 'platform=watchOS Simulator,name=$(SIM_WATCH)' \
		-derivedDataPath $(DERIVED) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build

watch-sim-json: deps
	xcodebuild -project $(PROJECT) -scheme SolstoneWatch \
		-skipMacroValidation \
		-destination 'platform=watchOS Simulator,name=$(SIM_WATCH)' \
		-derivedDataPath $(DERIVED) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build 2>&1 | xcsift

sim-launch:
	@set -eu; \
		udid='$(SIM_UDID)'; \
		if [ -z "$$udid" ]; then \
			test -s "$(SIM_UDID_FILE)" || { echo "error: simulator ownership file is missing: $(SIM_UDID_FILE)"; exit 1; }; \
			udid=$$(cat "$(SIM_UDID_FILE)"); \
		fi; \
		$(MAKE) sim SIM_UDID="$$udid"; \
		xcrun simctl boot "$$udid" >/dev/null 2>&1 || true; \
		xcrun simctl install "$$udid" $(SIM_APP); \
		xcrun simctl launch --console-pty --terminate-running-process "$$udid" $(BUNDLE_ID)

test: deps
	@rm -rf build/test-results.xcresult
	xcodebuild test -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM)' \
		-derivedDataPath $(DERIVED) \
		-resultBundlePath build/test-results.xcresult

ui-test: deps
	xcodebuild test -project $(PROJECT) -scheme $(SCHEME) \
		-only-testing:solstone-swiftUITests \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM)' \
		-derivedDataPath $(DERIVED)

integration-test: PORT ?= 7071
integration-test: sim
	@set -eu; \
	MOCK_PID=""; \
	LAUNCH_PID=""; \
	MOCK_LOG=$$(mktemp -t solstone-swift-mock.XXXXXX); \
	APP_LOG=$$(mktemp -t solstone-swift-app.XXXXXX); \
	BOOT_LOG=$$(mktemp -t solstone-swift-boot.XXXXXX); \
	cleanup() { \
		status=$$?; \
		if xcrun simctl terminate booted $(BUNDLE_ID) >/dev/null 2>&1; then :; fi; \
		if [ -n "$$LAUNCH_PID" ] && kill -0 "$$LAUNCH_PID" 2>/dev/null; then kill "$$LAUNCH_PID" 2>/dev/null; fi; \
		if [ -n "$$MOCK_PID" ] && kill -0 "$$MOCK_PID" 2>/dev/null; then kill "$$MOCK_PID" 2>/dev/null; fi; \
		rm -f "$$MOCK_LOG" "$$APP_LOG" "$$BOOT_LOG"; \
		exit $$status; \
	}; \
	trap cleanup EXIT INT TERM; \
	if ! xcrun simctl boot "$(SIM)" >"$$BOOT_LOG" 2>&1; then \
		if ! grep -q "Booted" "$$BOOT_LOG"; then \
			cat "$$BOOT_LOG"; \
			exit 1; \
		fi; \
	fi; \
	python3 test/mock_hub_phone.py --port $(PORT) >"$$MOCK_LOG" 2>&1 & \
	MOCK_PID=$$!; \
	ready=0; \
	for _ in 1 2 3 4 5; do \
		if grep -q "^READY:$(PORT)$$" "$$MOCK_LOG"; then \
			ready=1; \
			break; \
		fi; \
		if ! kill -0 "$$MOCK_PID" 2>/dev/null; then \
			echo "mock hub-phone exited before becoming ready (port $(PORT) may be in use):"; \
			cat "$$MOCK_LOG"; \
			exit 1; \
		fi; \
		sleep 1; \
	done; \
	if [ "$$ready" -ne 1 ]; then \
		echo "mock hub-phone did not become ready"; \
		cat "$$MOCK_LOG"; \
		exit 1; \
	fi; \
	xcrun simctl install booted $(SIM_APP); \
	SIMCTL_CHILD_MOCK_PORT=$(PORT) xcrun simctl launch --console-pty --terminate-running-process booted $(BUNDLE_ID) --integration-test >"$$APP_LOG" 2>&1 & \
	LAUNCH_PID=$$!; \
	pulse_seen=0; \
	for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do \
		if grep -q '"GET /app/home/api/pulse HTTP/1.1"' "$$MOCK_LOG"; then \
			pulse_seen=1; \
			break; \
		fi; \
		sleep 1; \
	done; \
	if [ "$$pulse_seen" -ne 1 ]; then \
		echo "integration-test failed: missing home pulse request"; \
		echo "--- subsystem log tail ---"; \
		xcrun simctl spawn booted log show --info --last 30s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 80; \
		echo "--- app log tail ---"; \
		tail -n 80 "$$APP_LOG"; \
		echo "--- mock log ---"; \
		cat "$$MOCK_LOG"; \
		exit 1; \
	fi; \
	echo "--- subsystem log tail ---"; \
	xcrun simctl spawn booted log show --info --last 10s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 20; \
	echo "integration-test passed"; \
	tail -n 20 "$$APP_LOG"

integration-test-live: PORT ?= 7071
integration-test-live: sim
	@set -eu; \
	LAUNCH_PID=""; \
	APP_LOG=$$(mktemp -t solstone-swift-live-app.XXXXXX); \
	BOOT_LOG=$$(mktemp -t solstone-swift-live-boot.XXXXXX); \
	cleanup() { \
		status=$$?; \
		if xcrun simctl terminate booted $(BUNDLE_ID) >/dev/null 2>&1; then :; fi; \
		if [ -n "$$LAUNCH_PID" ] && kill -0 "$$LAUNCH_PID" 2>/dev/null; then kill "$$LAUNCH_PID" 2>/dev/null; fi; \
		rm -f "$$APP_LOG" "$$BOOT_LOG"; \
		exit $$status; \
	}; \
	trap cleanup EXIT INT TERM; \
	if ! xcrun simctl boot "$(SIM)" >"$$BOOT_LOG" 2>&1; then \
		if ! grep -q "Booted" "$$BOOT_LOG"; then \
			cat "$$BOOT_LOG"; \
			exit 1; \
		fi; \
	fi; \
	xcrun simctl install booted $(SIM_APP); \
	SIMCTL_CHILD_LIVE_SERVER=$(SERVER) SIMCTL_CHILD_LIVE_PORT=$(PORT) xcrun simctl launch --console-pty --terminate-running-process booted $(BUNDLE_ID) --integration-test-live >"$$APP_LOG" 2>&1 & \
	LAUNCH_PID=$$!; \
	sleep 10; \
		echo "--- subsystem log tail ---"; \
		xcrun simctl spawn booted log show --info --last 15s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 40; \
		echo "integration-test-live launched"; \
		tail -n 40 "$$APP_LOG"

integration-test-push: PORT ?= 7071
integration-test-push: PUSH_PORT ?= 8474
integration-test-push: PUSH_TAP ?= briefing
integration-test-push: PUSH_ASSERT ?= routed to today
integration-test-push: PUSH_TARGET_NAME ?= integration-test-push
integration-test-push: sim
	@set -eu; \
		MOCK_PID=""; \
		PUSH_MOCK_PID=""; \
		LAUNCH_PID=""; \
		MOCK_LOG=$$(mktemp -t solstone-swift-mock.XXXXXX); \
		PUSH_MOCK_LOG=$$(mktemp -t solstone-swift-push-mock.XXXXXX); \
		PUSH_COUNT=$$(mktemp -t solstone-swift-push-count.XXXXXX); \
		APP_LOG=$$(mktemp -t solstone-swift-push-app.XXXXXX); \
		BOOT_LOG=$$(mktemp -t solstone-swift-push-boot.XXXXXX); \
		cleanup() { \
			status=$$?; \
			if xcrun simctl terminate booted $(BUNDLE_ID) >/dev/null 2>&1; then :; fi; \
			if [ -n "$$LAUNCH_PID" ] && kill -0 "$$LAUNCH_PID" 2>/dev/null; then kill "$$LAUNCH_PID" 2>/dev/null; fi; \
			if [ -n "$$MOCK_PID" ] && kill -0 "$$MOCK_PID" 2>/dev/null; then kill "$$MOCK_PID" 2>/dev/null; fi; \
			if [ -n "$$PUSH_MOCK_PID" ] && kill -0 "$$PUSH_MOCK_PID" 2>/dev/null; then kill "$$PUSH_MOCK_PID" 2>/dev/null; fi; \
			rm -f "$$MOCK_LOG" "$$PUSH_MOCK_LOG" "$$PUSH_COUNT" "$$APP_LOG" "$$BOOT_LOG"; \
			exit $$status; \
		}; \
		trap cleanup EXIT INT TERM; \
		if ! xcrun simctl boot "$(SIM)" >"$$BOOT_LOG" 2>&1; then \
			if ! grep -q "Booted" "$$BOOT_LOG"; then \
				cat "$$BOOT_LOG"; \
				exit 1; \
			fi; \
		fi; \
		for port in $(PORT) $(PUSH_PORT); do \
			pids=$$(lsof -tiTCP:$$port -sTCP:LISTEN 2>/dev/null || true); \
			if [ -n "$$pids" ]; then \
				kill $$pids 2>/dev/null || true; \
				sleep 1; \
			fi; \
		done; \
		python3 test/mock_hub_phone.py --port $(PORT) >"$$MOCK_LOG" 2>&1 & \
		MOCK_PID=$$!; \
		python3 test/mock_push_server.py --port $(PUSH_PORT) --count-file "$$PUSH_COUNT" >"$$PUSH_MOCK_LOG" 2>&1 & \
		PUSH_MOCK_PID=$$!; \
		ready=0; \
		for _ in 1 2 3 4 5; do \
			if grep -q "^READY:$(PORT)$$" "$$MOCK_LOG"; then ready=1; break; fi; \
			if ! kill -0 "$$MOCK_PID" 2>/dev/null; then cat "$$MOCK_LOG"; exit 1; fi; \
			sleep 1; \
		done; \
		[ "$$ready" -eq 1 ] || { echo "mock hub-phone did not become ready"; cat "$$MOCK_LOG"; exit 1; }; \
		push_ready=0; \
		for _ in 1 2 3 4 5; do \
			if grep -q "^READY:$(PUSH_PORT)$$" "$$PUSH_MOCK_LOG"; then push_ready=1; break; fi; \
			if ! kill -0 "$$PUSH_MOCK_PID" 2>/dev/null; then cat "$$PUSH_MOCK_LOG"; exit 1; fi; \
			sleep 1; \
		done; \
		[ "$$push_ready" -eq 1 ] || { echo "mock push server did not become ready"; cat "$$PUSH_MOCK_LOG"; exit 1; }; \
		xcrun simctl install booted $(SIM_APP); \
		SIMCTL_CHILD_MOCK_PORT=$(PORT) SIMCTL_CHILD_MOCK_PUSH_PORT=$(PUSH_PORT) xcrun simctl launch --console-pty --terminate-running-process booted $(BUNDLE_ID) --integration-test --integration-test-push-register --integration-test-push-tap=$(PUSH_TAP) >"$$APP_LOG" 2>&1 & \
		LAUNCH_PID=$$!; \
		positive=0; \
		for _ in 1 2 3 4 5 6 7 8 9 10; do \
			if xcrun simctl spawn booted log show --info --last 5s --predicate 'subsystem == "$(LOG_SUB)" AND category == "router"' 2>/dev/null | grep -q "$(PUSH_ASSERT)"; then positive=1; break; fi; \
			sleep 1; \
		done; \
		[ "$$positive" -eq 1 ] || { echo "$(PUSH_TARGET_NAME) failed: missing $(PUSH_ASSERT) log"; xcrun simctl spawn booted log show --info --last 20s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 80; exit 1; }; \
		if ! curl -s "http://127.0.0.1:$(PUSH_PORT)/api/push/status" | grep -Eq '"registration_count"[[:space:]]*:[[:space:]]*[1-9]'; then \
			echo "$(PUSH_TARGET_NAME) failed: mock push server never saw registration"; \
			cat "$$PUSH_COUNT"; \
			cat "$$PUSH_MOCK_LOG"; \
			exit 1; \
		fi; \
		echo "--- subsystem log tail ---"; \
		xcrun simctl spawn booted log show --info --last 10s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 40; \
		echo "$(PUSH_TARGET_NAME) passed"; \
		tail -n 20 "$$APP_LOG"

integration-test-observer: PORT ?= 7071
integration-test-observer: PUSH_PORT ?= 8474
integration-test-observer: OBSERVER_PORT ?= 8575
integration-test-observer: sim
	@set -eu; \
		MOCK_PID=""; \
		PUSH_MOCK_PID=""; \
		OBSERVER_MOCK_PID=""; \
		LAUNCH_PID=""; \
		MOCK_LOG=$$(mktemp -t solstone-swift-mock.XXXXXX); \
		PUSH_MOCK_LOG=$$(mktemp -t solstone-swift-push-mock.XXXXXX); \
		OBSERVER_MOCK_LOG=$$(mktemp -t solstone-swift-observer-mock.XXXXXX); \
		PUSH_COUNT=$$(mktemp -t solstone-swift-push-count.XXXXXX); \
		OBSERVER_COUNT=$$(mktemp -t solstone-swift-observer-count.XXXXXX); \
		SENSE_APP_LOG=$$(mktemp -t solstone-swift-observer-sense.XXXXXX); \
		BOOT_LOG=$$(mktemp -t solstone-swift-observer-boot.XXXXXX); \
		observer_upload_count() { \
			curl -s "http://127.0.0.1:$(OBSERVER_PORT)/api/observer/status" | python3 -c 'import json,sys; data=sys.stdin.read(); print((json.loads(data).get("upload_count", 0) if data else 0))' 2>/dev/null || echo 0; \
		}; \
		cleanup() { \
			status=$$?; \
			if xcrun simctl terminate booted $(BUNDLE_ID) >/dev/null 2>&1; then :; fi; \
			if [ -n "$$LAUNCH_PID" ] && kill -0 "$$LAUNCH_PID" 2>/dev/null; then kill "$$LAUNCH_PID" 2>/dev/null; fi; \
			if [ -n "$$MOCK_PID" ] && kill -0 "$$MOCK_PID" 2>/dev/null; then kill "$$MOCK_PID" 2>/dev/null; fi; \
			if [ -n "$$PUSH_MOCK_PID" ] && kill -0 "$$PUSH_MOCK_PID" 2>/dev/null; then kill "$$PUSH_MOCK_PID" 2>/dev/null; fi; \
			if [ -n "$$OBSERVER_MOCK_PID" ] && kill -0 "$$OBSERVER_MOCK_PID" 2>/dev/null; then kill "$$OBSERVER_MOCK_PID" 2>/dev/null; fi; \
			rm -f "$$MOCK_LOG" "$$PUSH_MOCK_LOG" "$$OBSERVER_MOCK_LOG" "$$PUSH_COUNT" "$$OBSERVER_COUNT" "$$SENSE_APP_LOG" "$$BOOT_LOG"; \
			exit $$status; \
		}; \
		trap cleanup EXIT INT TERM; \
		if ! xcrun simctl boot "$(SIM)" >"$$BOOT_LOG" 2>&1; then \
			if ! grep -q "Booted" "$$BOOT_LOG"; then \
				cat "$$BOOT_LOG"; \
				exit 1; \
			fi; \
		fi; \
		for port in $(PORT) $(PUSH_PORT) $(OBSERVER_PORT); do \
			pids=$$(lsof -tiTCP:$$port -sTCP:LISTEN 2>/dev/null || true); \
			if [ -n "$$pids" ]; then \
				kill $$pids 2>/dev/null || true; \
				sleep 1; \
			fi; \
		done; \
		python3 test/mock_hub_phone.py --port $(PORT) >"$$MOCK_LOG" 2>&1 & \
		MOCK_PID=$$!; \
		python3 test/mock_push_server.py --port $(PUSH_PORT) --count-file "$$PUSH_COUNT" >"$$PUSH_MOCK_LOG" 2>&1 & \
		PUSH_MOCK_PID=$$!; \
		python3 test/mock_observer_server.py --port $(OBSERVER_PORT) --count-file "$$OBSERVER_COUNT" >"$$OBSERVER_MOCK_LOG" 2>&1 & \
		OBSERVER_MOCK_PID=$$!; \
		ready=0; \
		for _ in 1 2 3 4 5; do \
			if grep -q "^READY:$(PORT)$$" "$$MOCK_LOG"; then ready=1; break; fi; \
			if ! kill -0 "$$MOCK_PID" 2>/dev/null; then cat "$$MOCK_LOG"; exit 1; fi; \
			sleep 1; \
		done; \
		[ "$$ready" -eq 1 ] || { echo "mock hub-phone did not become ready"; cat "$$MOCK_LOG"; exit 1; }; \
		push_ready=0; \
		for _ in 1 2 3 4 5; do \
			if grep -q "^READY:$(PUSH_PORT)$$" "$$PUSH_MOCK_LOG"; then push_ready=1; break; fi; \
			if ! kill -0 "$$PUSH_MOCK_PID" 2>/dev/null; then cat "$$PUSH_MOCK_LOG"; exit 1; fi; \
			sleep 1; \
		done; \
		[ "$$push_ready" -eq 1 ] || { echo "mock push server did not become ready"; cat "$$PUSH_MOCK_LOG"; exit 1; }; \
		observer_ready=0; \
		for _ in 1 2 3 4 5; do \
			if grep -q "^READY:$(OBSERVER_PORT)$$" "$$OBSERVER_MOCK_LOG"; then observer_ready=1; break; fi; \
			if ! kill -0 "$$OBSERVER_MOCK_PID" 2>/dev/null; then cat "$$OBSERVER_MOCK_LOG"; exit 1; fi; \
			sleep 1; \
		done; \
		[ "$$observer_ready" -eq 1 ] || { echo "mock observer server did not become ready"; cat "$$OBSERVER_MOCK_LOG"; exit 1; }; \
		xcrun simctl install booted $(SIM_APP); \
		SIMCTL_CHILD_MOCK_PORT=$(PORT) SIMCTL_CHILD_MOCK_PUSH_PORT=$(PUSH_PORT) SIMCTL_CHILD_MOCK_OBSERVER_PORT=$(OBSERVER_PORT) xcrun simctl launch --console-pty --terminate-running-process booted $(BUNDLE_ID) --integration-test --integration-test-observer-reset-registration --integration-test-observer-tap=sense >"$$SENSE_APP_LOG" 2>&1 & \
		LAUNCH_PID=$$!; \
		sense_started=0; \
		for _ in 1 2 3 4 5 6 7 8 9 10; do \
			if xcrun simctl spawn booted log show --info --last 5s --predicate 'subsystem == "$(LOG_SUB)" AND category == "observer"' 2>/dev/null | grep -q "observer: session starting"; then sense_started=1; break; fi; \
			sleep 1; \
		done; \
		[ "$$sense_started" -eq 1 ] || { echo "integration-test-observer failed: sense path never started observer"; xcrun simctl spawn booted log show --info --last 20s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 80; tail -n 80 "$$SENSE_APP_LOG"; exit 1; }; \
		sense_upload_start=$$(observer_upload_count); \
		sense_uploaded=0; \
		for _ in 1 2 3 4 5 6 7 8 9 10 11 12; do \
			sense_upload_now=$$(observer_upload_count); \
			if [ "$$sense_upload_now" -gt "$$sense_upload_start" ]; then sense_uploaded=1; break; fi; \
			sleep 1; \
		done; \
		[ "$$sense_uploaded" -eq 1 ] || { echo "integration-test-observer failed: sense path never uploaded mobile segment"; xcrun simctl spawn booted log show --info --last 30s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 80; tail -n 80 "$$SENSE_APP_LOG"; exit 1; }; \
		if ! curl -s "http://127.0.0.1:$(OBSERVER_PORT)/api/observer/status" | grep -Eq '"upload_count"[[:space:]]*:[[:space:]]*[1-9]'; then \
			echo "integration-test-observer failed: sense path upload missing"; \
			cat "$$OBSERVER_COUNT"; \
			cat "$$OBSERVER_MOCK_LOG"; \
			exit 1; \
		fi; \
		if ! curl -s "http://127.0.0.1:$(OBSERVER_PORT)/api/observer/status" | grep -Eq '"filename"[[:space:]]*:[[:space:]]*"audio.m4a"'; then \
			echo "integration-test-observer failed: sense path upload filename invariant missing"; \
			cat "$$OBSERVER_COUNT"; \
			cat "$$OBSERVER_MOCK_LOG"; \
			exit 1; \
		fi; \
		if ! curl -s "http://127.0.0.1:$(OBSERVER_PORT)/api/observer/status" | grep -Eq '"protocol_version"[[:space:]]*:[[:space:]]*"3"'; then \
			echo "integration-test-observer failed: v3 protocol header missing"; \
			cat "$$OBSERVER_COUNT"; \
			exit 1; \
		fi; \
		if curl -s "http://127.0.0.1:$(OBSERVER_PORT)/api/observer/status" | grep -Eq '"authorization"[[:space:]]*:[[:space:]]*"Bearer '; then \
			echo "integration-test-observer failed: ingest sent authorization"; \
			cat "$$OBSERVER_COUNT"; \
			exit 1; \
		fi; \
		sleep 5; \
		registration_count=$$(xcrun simctl spawn booted log show --info --last 120s --predicate 'subsystem == "$(LOG_SUB)" AND category == "registration"' 2>/dev/null | grep -c "observer registration succeeded" || true); \
		[ "$$registration_count" -eq 0 ] || { echo "integration-test-observer failed: linked-device ingest registered $$registration_count times"; xcrun simctl spawn booted log show --info --last 120s --predicate 'subsystem == "$(LOG_SUB)" AND category == "registration"' 2>/dev/null; exit 1; }; \
		if ! curl -s "http://127.0.0.1:$(OBSERVER_PORT)/api/observer/status" | grep -Eq '"create_count"[[:space:]]*:[[:space:]]*0'; then \
			echo "integration-test-observer failed: linked-device ingest registered"; \
			cat "$$OBSERVER_COUNT"; \
			cat "$$OBSERVER_MOCK_LOG"; \
			exit 1; \
		fi; \
		echo "--- subsystem log tail ---"; \
		xcrun simctl spawn booted log show --info --last 10s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 40; \
		echo "integration-test-observer passed"; \
		tail -n 20 "$$SENSE_APP_LOG"

integration-test-onboarding: PAIRING_PORT ?= 8676
integration-test-onboarding: sim
	@set -eu; \
		PAIRING_MOCK_PID=""; \
		LAUNCH_PID=""; \
		PAIRING_MOCK_LOG=$$(mktemp -t solstone-swift-pairing-mock.XXXXXX); \
		PAIRING_COUNT=$$(mktemp -t solstone-swift-pairing-count.XXXXXX); \
		APP_LOG=$$(mktemp -t solstone-swift-onboarding-app.XXXXXX); \
		BOOT_LOG=$$(mktemp -t solstone-swift-onboarding-boot.XXXXXX); \
		cleanup() { \
			status=$$?; \
			if xcrun simctl terminate booted $(BUNDLE_ID) >/dev/null 2>&1; then :; fi; \
			if [ -n "$$LAUNCH_PID" ] && kill -0 "$$LAUNCH_PID" 2>/dev/null; then kill "$$LAUNCH_PID" 2>/dev/null; fi; \
			if [ -n "$$PAIRING_MOCK_PID" ] && kill -0 "$$PAIRING_MOCK_PID" 2>/dev/null; then kill "$$PAIRING_MOCK_PID" 2>/dev/null; fi; \
			rm -f "$$PAIRING_MOCK_LOG" "$$PAIRING_COUNT" "$$APP_LOG" "$$BOOT_LOG"; \
			exit $$status; \
		}; \
		trap cleanup EXIT INT TERM; \
		if ! xcrun simctl boot "$(SIM)" >"$$BOOT_LOG" 2>&1; then \
			if ! grep -q "Booted" "$$BOOT_LOG"; then \
				cat "$$BOOT_LOG"; \
				exit 1; \
			fi; \
		fi; \
		pids=$$(lsof -tiTCP:$(PAIRING_PORT) -sTCP:LISTEN 2>/dev/null || true); \
		if [ -n "$$pids" ]; then kill $$pids 2>/dev/null || true; sleep 1; fi; \
		python3 test/mock_pairing_server.py --port $(PAIRING_PORT) --count-file "$$PAIRING_COUNT" >"$$PAIRING_MOCK_LOG" 2>&1 & \
		PAIRING_MOCK_PID=$$!; \
		pairing_ready=0; \
		for _ in 1 2 3 4 5; do \
			if grep -q "^READY:$(PAIRING_PORT)$$" "$$PAIRING_MOCK_LOG"; then pairing_ready=1; break; fi; \
			if ! kill -0 "$$PAIRING_MOCK_PID" 2>/dev/null; then cat "$$PAIRING_MOCK_LOG"; exit 1; fi; \
			sleep 1; \
		done; \
		[ "$$pairing_ready" -eq 1 ] || { echo "mock pairing server did not become ready"; cat "$$PAIRING_MOCK_LOG"; exit 1; }; \
		xcrun simctl install booted $(SIM_APP); \
		ONBOARDING_START=$$(date +"%Y-%m-%d %H:%M:%S"); \
		SIMCTL_CHILD_MOCK_PAIRING_PORT=$(PAIRING_PORT) xcrun simctl launch --console-pty --terminate-running-process booted $(BUNDLE_ID) --integration-test-onboarding >"$$APP_LOG" 2>&1 & \
		LAUNCH_PID=$$!; \
		completed=0; \
		for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do \
			if xcrun simctl spawn booted log show --info --start "$$ONBOARDING_START" --predicate 'subsystem == "$(LOG_SUB)" AND category == "onboarding"' 2>/dev/null | grep -q "onboarding completed"; then completed=1; break; fi; \
			sleep 1; \
		done; \
		[ "$$completed" -eq 1 ] || { echo "integration-test-onboarding failed: onboarding did not complete"; xcrun simctl spawn booted log show --info --last 40s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 120; tail -n 120 "$$APP_LOG"; cat "$$PAIRING_MOCK_LOG"; exit 1; }; \
		PAIRING_STATUS=$$(curl -fsS "http://127.0.0.1:$(PAIRING_PORT)/api/pairing/status") || { echo "integration-test-onboarding failed: could not read pairing status from mock server"; cat "$$PAIRING_MOCK_LOG"; exit 1; }; \
		echo "$$PAIRING_STATUS" | grep -Eq '"confirm_count"[[:space:]]*:[[:space:]]*0' || { echo "integration-test-onboarding failed: onboarding unexpectedly confirmed pairing"; echo "$$PAIRING_STATUS"; cat "$$PAIRING_MOCK_LOG"; exit 1; }; \
		echo "$$PAIRING_STATUS" | grep -Eq '"push_register_count"[[:space:]]*:[[:space:]]*0' || { echo "integration-test-onboarding failed: onboarding unexpectedly registered for push"; echo "$$PAIRING_STATUS"; cat "$$PAIRING_MOCK_LOG"; exit 1; }; \
		echo "$$PAIRING_STATUS" | grep -Eq '"briefing_updates"[[:space:]]*:[[:space:]]*\[\]' || { echo "integration-test-onboarding failed: onboarding unexpectedly updated briefing time"; echo "$$PAIRING_STATUS"; cat "$$PAIRING_MOCK_LOG"; exit 1; }; \
		echo "--- subsystem log tail ---"; \
		xcrun simctl spawn booted log show --info --last 10s --predicate 'subsystem == "$(LOG_SUB)"' 2>/dev/null | tail -n 40; \
		echo "integration-test-onboarding passed"; \
		tail -n 20 "$$APP_LOG"

# Canonical pre-ship gate: brand/a11y/casing assertions (cheap, fail-fast) then a
# full build + test pass. Run this before merging any branch to main.
# The test phase goes through test/run_ci_tests.sh: a timeout-guarded, retry-once
# wrapper that never hangs and never masks a real failure (host-side UITest-runner
# flake resistance). Override CI_* vars above to tune timeout/runtime/attempts.
ci: deps
	bash test/assert_brand_canon.sh
	bash test/assert_accessibility_hints.sh
	bash test/assert_haptics_gated.sh
	bash test/assert_tap_targets.sh
	bash test/assert_casing.sh
	bash test/assert_no_emdash.sh
	bash test/assert_no_devcopy.sh
	bash test/assert_background_modes.sh
	bash test/assert_watch_background_modes.sh
	bash test/assert_watch_privacy.sh
	bash test/assert_broadcast_privacy.sh
	PROJECT='$(PROJECT)' SCHEME='$(SCHEME)' DERIVED='$(DERIVED)' \
		CI_SIM_NAME='$(CI_SIM_NAME)' CI_SIM_DEVICETYPE='$(CI_SIM_DEVICETYPE)' \
		CI_SIM_RUNTIME='$(CI_SIM_RUNTIME)' CI_ATTEMPT_TIMEOUT='$(CI_ATTEMPT_TIMEOUT)' \
		CI_MAX_ATTEMPTS='$(CI_MAX_ATTEMPTS)' bash test/run_ci_tests.sh
	$(MAKE) ci-watch

ci-watch: deps
	PROJECT='$(PROJECT)' SCHEME='SolstoneWatch' DERIVED='$(DERIVED)' \
		CI_TEST_LANE='watch' CI_SIM_PLATFORM='watchOS Simulator' \
		CI_SIM_NAME='$(CI_WATCH_SIM_NAME)' CI_SIM_DEVICETYPE='$(CI_WATCH_SIM_DEVICETYPE)' \
		CI_SIM_RUNTIME='$(CI_WATCH_SIM_RUNTIME)' CI_ATTEMPT_TIMEOUT='$(CI_ATTEMPT_TIMEOUT)' \
		CI_MAX_ATTEMPTS='$(CI_MAX_ATTEMPTS)' bash test/run_ci_tests.sh

# The iPad test-execution lane. Until this existed the only iPad targets were
# `sim-ipad` and `sim-ipad-json`, both of which are `xcodebuild build` — so no line of
# this app had ever been EXECUTED on an iPad simulator, and an iPad acceptance
# criterion had no oracle behind it. Same runner, same classifier, same retry-once
# behaviour as the iPhone and watch lanes; artifacts are namespaced by CI_TEST_LANE.
ci-ipad: deps
	PROJECT='$(PROJECT)' SCHEME='$(SCHEME)' DERIVED='$(DERIVED)' \
		CI_TEST_LANE='ipad' \
		CI_SIM_NAME='$(CI_IPAD_SIM_NAME)' CI_SIM_DEVICETYPE='$(CI_IPAD_SIM_DEVICETYPE)' \
		CI_SIM_RUNTIME='$(CI_SIM_RUNTIME)' CI_ATTEMPT_TIMEOUT='$(CI_ATTEMPT_TIMEOUT)' \
		CI_MAX_ATTEMPTS='$(CI_MAX_ATTEMPTS)' bash test/run_ci_tests.sh

# Capture launch-state screenshots on an iPad instead of the iPhone. No target change
# was needed: `sim` builds one universal Debug-iphonesimulator product and SIM_DESTINATION
# derives from SIM, so overriding SIM alone retargets both the build and the boot.
sim-shots-ipad:
	$(MAKE) sim-shots SIM='$(SIM_IPAD)'

# Validate the CI runner's trust-critical classification logic (no simulator needed).
ci-selftest:
	bash test/run_ci_tests.sh --selftest

test-one: deps
	xcodebuild test -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM)' \
		-derivedDataPath $(DERIVED) \
		-only-testing:'$(SCHEME)Tests/$(TEST)'

test-build: deps
	xcodebuild build-for-testing -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM)' \
		-derivedDataPath $(DERIVED)

test-fast:
	xcodebuild test-without-building \
		-project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-destination 'platform=iOS Simulator,name=$(SIM)' \
		-derivedDataPath $(DERIVED)

# --- Device (requires iPhone connected to Mac) ---

build: deps unlock
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-allowProvisioningUpdates \
		-destination 'id=$(DEVICE)' \
		-derivedDataPath $(DERIVED) \
		DEVELOPMENT_TEAM=$(TEAM_ID) \
		COMPILATION_CACHE_ENABLE_CACHING=YES \
		build

# Device-family signing build without a connected device.
build-generic: deps unlock
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-allowProvisioningUpdates \
		-destination 'generic/platform=iOS' \
		-derivedDataPath $(DERIVED) \
		DEVELOPMENT_TEAM=$(TEAM_ID) \
		build

release: deps unlock
	xcodebuild archive -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-configuration Release \
		-archivePath $(ARCHIVE) \
		-destination 'id=$(DEVICE)' \
		-derivedDataPath $(DERIVED) \
		DEVELOPMENT_TEAM=$(TEAM_ID)

# === TestFlight distribution (App Store Connect internal testing) ===
# Requires config/testflight.env (see the operator-config block near the top).

# Fail early with a clear message if operator config is missing.
check-asc-config:
	@test -n "$(ASC_KEY_ID)" && test -n "$(ASC_ISSUER)" && test -n "$(ASC_KEY_PATH)" || { \
		echo "error: App Store Connect config missing — create config/testflight.env"; \
		echo "       (copy config/testflight.env.example and fill in your values)"; exit 1; }
	@test -f "$(ASC_KEY_PATH)" || { echo "error: ASC API key not found at: $(ASC_KEY_PATH)"; exit 1; }

# Distribution-signed archive (generic iOS; App Store provisioning via the ASC key).
release-distribution: deps unlock check-asc-config
	xcodebuild archive -project $(PROJECT) -scheme $(SCHEME) \
		-skipMacroValidation \
		-configuration Release \
		-archivePath $(ARCHIVE_DISTRIBUTION) \
		-destination 'generic/platform=iOS' \
		-derivedDataPath $(DERIVED) \
		-allowProvisioningUpdates \
		-authenticationKeyPath $(ASC_KEY_PATH) \
		-authenticationKeyID $(ASC_KEY_ID) \
		-authenticationKeyIssuerID $(ASC_ISSUER) \
		DEVELOPMENT_TEAM=$(TEAM_ID)

# Export the distribution archive to a signed App Store IPA.
# exportOptions is generated from TEAM_ID so the team is single-sourced.
ipa-appstore: release-distribution
	rm -rf build/ipa-appstore
	@mkdir -p build
	@{ \
		echo '<?xml version="1.0" encoding="UTF-8"?>'; \
		echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'; \
		echo '<plist version="1.0">'; \
		echo '<dict>'; \
		echo '  <key>method</key><string>app-store-connect</string>'; \
		echo '  <key>teamID</key><string>$(TEAM_ID)</string>'; \
		echo '  <key>signingStyle</key><string>automatic</string>'; \
		echo '  <key>uploadSymbols</key><true/>'; \
		echo '  <key>uploadBitcode</key><false/>'; \
		echo '  <key>destination</key><string>export</string>'; \
		echo '  <key>manageAppVersionAndBuildNumber</key><false/>'; \
		echo '</dict>'; \
		echo '</plist>'; \
	} > build/exportOptions-AppStore.plist
	xcodebuild -exportArchive \
		-archivePath $(ARCHIVE_DISTRIBUTION) \
		-exportPath build/ipa-appstore \
		-exportOptionsPlist build/exportOptions-AppStore.plist \
		-allowProvisioningUpdates \
		-authenticationKeyPath $(ASC_KEY_PATH) \
		-authenticationKeyID $(ASC_KEY_ID) \
		-authenticationKeyIssuerID $(ASC_ISSUER)

# Upload the exported IPA to App Store Connect for TestFlight processing.
testflight-upload: ipa-appstore
	xcrun altool --upload-app \
		--type ios \
		--file "$$(ls build/ipa-appstore/*.ipa | head -1)" \
		--apiKey $(ASC_KEY_ID) \
		--apiIssuer $(ASC_ISSUER) \
		--p8-file-path $(ASC_KEY_PATH)

# Full pipeline: upload, wait for processing, clear export compliance,
# attach to the internal group, and wait for IN_BETA_TESTING.
testflight: testflight-release

testflight-release: testflight-upload
	@test -n "$(TESTFLIGHT_GROUP)" || { echo "error: TESTFLIGHT_GROUP not set (config/testflight.env)"; exit 1; }
	notify_arg=""; \
	if [ "$(TESTFLIGHT_NOTIFY)" = "true" ]; then notify_arg="--notify"; fi; \
	python3 -u scripts/release-testflight.py \
		--bundle-id "$(BUNDLE_ID)" \
		--group-name "$(TESTFLIGHT_GROUP)" \
		--key-id "$(ASC_KEY_ID)" \
		--issuer-id "$(ASC_ISSUER)" \
		--key-path "$(ASC_KEY_PATH)" \
		$$notify_arg

deploy: build
	@tmux kill-window -t hopper:logs 2>/dev/null || true
	@rm -f $(DEVICE_LOG)
	@tmux new-window -t hopper: -d -n logs \
		"pymobiledevice3 syslog live --tunnel '' 2>&1 | grep --line-buffered solstone-swift | tee $(DEVICE_LOG)"
	@sleep 2
	xcrun devicectl device install app --device $(DEVICE) $(DEV_APP)
	@echo "Deployed — logs streaming to $(DEVICE_LOG)"

launch:
	xcrun devicectl device process launch --console --device $(DEVICE) $(BUNDLE_ID)

cycle: deploy launch

run: deploy
	xcrun devicectl device process launch --device $(DEVICE) $(BUNDLE_ID)

# --- Device debugging (requires pymobiledevice3 tunneld running) ---

# Simulator screenshots across the accessibility matrix, for visual validation.
# Validation for the mobile-shell arc is the simulator plus screenshots; this is that
# instrument. NOTE: the `screenshot` target below is the DEVICE path and is unrelated.
sim-shots: sim
	SHOTS_APP="$(DERIVED)/Build/Products/Debug-iphonesimulator/$(SCHEME).app" \
		SHOTS_SIM="$(SIM)" \
		$(if $(SHOTS_STATES),SHOTS_STATES="$(SHOTS_STATES)") \
		bash test/capture_shots.sh

# Widget gallery / Lock Screen screenshots use the lode-exclusive output path above.
sim-widget-shots: sim
	WIDGET_SHOTS_APP="$(SIM_APP)" \
		WIDGET_SHOTS_BUNDLE_ID="$(BUNDLE_ID)" \
		WIDGET_SHOTS_OUT="$(WIDGET_SHOTS_OUT)" \
		WIDGET_SHOTS_SIM="$(SIM)" \
		bash test/capture_widget_screenshots.sh

screenshot:
	@pymobiledevice3 developer dvt screenshot /tmp/solstone-swift-screenshot.png --tunnel '' 2>&1 || \
		{ echo "error: run 'sudo pymobiledevice3 remote tunneld' on the Mac first"; exit 1; }
	@echo "Screenshot: /tmp/solstone-swift-screenshot.png"

logs:
	@cat $(DEVICE_LOG) 2>/dev/null || echo "No logs. Run 'make run' to deploy with log capture."

logs-collect:
	sudo log collect --device-udid $(DEVICE) --output /tmp/solstone-swift-logs.logarchive
	@echo "Collected to /tmp/solstone-swift-logs.logarchive"
	@echo "View with: log show --predicate 'subsystem == \"$(LOG_SUB)\"' /tmp/solstone-swift-logs.logarchive"

log-show:
	log show --predicate 'subsystem == "$(LOG_SUB)"' --style compact /tmp/solstone-swift-logs.logarchive

crash:
	pymobiledevice3 crash pull /tmp/solstone-swift-crashes --tunnel '' 2>&1 || \
		idevicecrashreport /tmp/solstone-swift-crashes 2>&1 || \
		{ echo "error: install pymobiledevice3 or libimobiledevice"; exit 1; }
	@echo "Crash reports: /tmp/solstone-swift-crashes/"

# --- Utilities ---

signing-check:
	@echo "=== Signing Identities ==="
	@security find-identity -p codesigning -v
	@echo ""
	@echo "=== Team: $(TEAM_ID) ==="
	@echo "=== Bundle: $(BUNDLE_ID) ==="
	@echo ""
	@echo "=== Provisioning Profiles ==="
	@ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | while read p; do \
		name=$$(security cms -D -i "$$p" 2>/dev/null | plutil -extract Name raw - 2>/dev/null); \
		team=$$(security cms -D -i "$$p" 2>/dev/null | plutil -extract TeamIdentifier.0 raw - 2>/dev/null); \
		echo "  $$name (team: $$team)"; \
	done || echo "  (none found)"
	@echo ""
	@if security find-identity -p codesigning -v | grep -q "Apple Development"; then \
		echo "OK: Apple Development certificate found"; \
	else \
		echo "MISSING: No Apple Development certificate. Add account in Xcode > Settings > Accounts."; \
	fi

devices:
	xcrun devicectl list devices

clean:
	xcodebuild clean -project $(PROJECT) -scheme $(SCHEME) -skipMacroValidation 2>/dev/null || true
	rm -rf build/ $(PROJECT)
